### ISSUE TITLE
BUR display issue - error parsing line

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#108] opened 2017-04-04 04:25 UTC
![tmp_2543-screenshot_20170404-0954191552920714](https://cloud.githubusercontent.com/assets/5755132/24641358/c611b608-191c-11e7-9d80-3363cc3355a8.png)

anujYA headword

**Comment by funderburkjim** [comment] 2017-04-05 23:40
I confirm the problem, and think it is now fixed.

Here is a description of the change.
In [main.js](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/web/webtc2/main.js) , in
function displayDB,  the 'sendData' variable passes the xml data for the entry to the php script query_multi, which uses the basicDisplay to turn the xml into html.

The problem appears to be caused by applying the Javascript 'escape' function to the xml data before sending it to query_multi.   When this escaping was removed,  the display functions properly.

My understanding of this fine point of web-programming is somewhat wobbly.

**Closed** 2017-04-15 17:16 UTC
