### ISSUE TITLE
Wrongly Parsed Abbreviations

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#245] opened 2019-01-10 20:27 UTC
In MW was looking at `sāraṅga m. (ifc. f(ā). ) a kind of spotted antelope` and noticed a bug.

ifc. - is shown as `in fine compositi or`, but should be `in fine compositi or 'at the end of a compound'`

So because of `'at the end of a compound'` it is parsed only partly.

Check as well:
```
e.g.	exempli gratia, 'for example'
ib.	ibidem or 'in the same place or book or text' as the preceding
id.	idem or 'the same meaning as that of a preceding word'
ifc.	in fine compositi or 'at the end of a compound'
```

Scraped from https://www.sanskrit-lexicon.uni-koeln.de/monier/abbr.html

**Comment by funderburkjim** [comment] 2019-01-10 21:53
This problem is likely caused by the presence of the single quote character in the abbreviation text.
This text is inserted into the value of the title attribute of an html element which is constructed as
 a text string in php:  `"<span title='$tran'>"` where $tran is the string `exempli gratia, 'for example'`
So we have text which is in a single quote included in the single-quotations around `'$tran`, and I suspect this is the problem.

What is a foolproof way to do the above, so that quotations won't cause a problem?

Maybe one way would be to change the single quotes used in the abbreviation text to unicode opening and closing single quotes (which are different characters than the single quote).

Note There are also problems with '&' character when in tooltip text (as for lexical references) - I recently replaced these in the mw lexical source texts.

Any suggestions from web-dev experts?

**Comment by gasyoun** [comment] 2019-01-12 08:48
> Maybe one way would be to change the single quotes used in the abbreviation text to unicode opening and closing single quotes

Let's try.

>  (which are different characters than the single quote).

Not an issue.

**Closed as completed** 2019-01-14 20:25 UTC
Labels: bug

**Comment by gasyoun** [comment] 2019-01-15 08:48
> This fixes the bug.

Indeed, thanks.
